#############################################################################
# Makefile for building: BlsNetPlatformPro
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  BlsNetPlatformPro.pro
# Template: subdirs
# Command: F:\QT5.7\5.7\msvc2015\bin\qmake.exe -spec win32-msvc2015 -o Makefile BlsNetPlatformPro.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = F:\QT5.7\5.7\msvc2015\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-E--CPRGit-UI-UI-pro


sub-E--CPRGit-UI-UI-pro-qmake_all:  FORCE
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	cd UI\ && $(QMAKE) E:\CPRGit\UI\UI.pro -spec win32-msvc2015 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && $(MAKE) -f Makefile qmake_all
sub-E--CPRGit-UI-UI-pro: FORCE
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && ( if not exist Makefile $(QMAKE) E:\CPRGit\UI\UI.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile
sub-E--CPRGit-UI-UI-pro-make_first: FORCE
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && ( if not exist Makefile $(QMAKE) E:\CPRGit\UI\UI.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile 
sub-E--CPRGit-UI-UI-pro-all: FORCE
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && ( if not exist Makefile $(QMAKE) E:\CPRGit\UI\UI.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile all
sub-E--CPRGit-UI-UI-pro-clean: FORCE
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && ( if not exist Makefile $(QMAKE) E:\CPRGit\UI\UI.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile clean
sub-E--CPRGit-UI-UI-pro-distclean: FORCE
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && ( if not exist Makefile $(QMAKE) E:\CPRGit\UI\UI.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-E--CPRGit-UI-UI-pro-install_subtargets: FORCE
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && ( if not exist Makefile $(QMAKE) E:\CPRGit\UI\UI.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile install
sub-E--CPRGit-UI-UI-pro-uninstall_subtargets: FORCE
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && ( if not exist Makefile $(QMAKE) E:\CPRGit\UI\UI.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: BlsNetPlatformPro.pro F:\QT5.7\5.7\msvc2015\mkspecs\win32-msvc2015\qmake.conf F:\QT5.7\5.7\msvc2015\mkspecs\features\spec_pre.prf \
		F:\QT5.7\5.7\msvc2015\mkspecs\common\angle.conf \
		F:\QT5.7\5.7\msvc2015\mkspecs\common\msvc-base.conf \
		F:\QT5.7\5.7\msvc2015\mkspecs\common\msvc-desktop.conf \
		F:\QT5.7\5.7\msvc2015\mkspecs\qconfig.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dcore.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dcore_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dextras.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dextras_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dinput.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dinput_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dlogic.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dlogic_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dquick.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dquick_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickextras.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickinput.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickrender.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3drender.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3drender_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_axbase.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_axbase_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_axcontainer.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_axcontainer_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_axserver.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_axserver_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_bluetooth.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_bluetooth_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_bootstrap_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_charts.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_charts_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_clucene_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_concurrent.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_concurrent_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_core.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_core_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_dbus.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_dbus_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_designer.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_designer_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_designercomponents_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_gamepad.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_gamepad_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_gui.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_gui_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_help.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_help_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_location.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_location_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_multimedia.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_multimedia_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_multimediawidgets.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_network.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_network_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_nfc.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_nfc_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_opengl.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_opengl_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_openglextensions.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_openglextensions_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_platformsupport_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_positioning.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_positioning_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_printsupport.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_printsupport_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_purchasing.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_purchasing_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_qml.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_qml_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_qmldebug_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_qmltest.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_qmltest_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_quick.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_quick_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_quickcontrols2.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_quickparticles_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_quickwidgets.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_script.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_script_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_scripttools.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_scripttools_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_scxml.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_scxml_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_sensors.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_sensors_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_serialbus.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_serialbus_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_serialport.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_serialport_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_sql.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_sql_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_svg.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_svg_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_testlib.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_testlib_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_uiplugin.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_uitools.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_uitools_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_webchannel.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_webchannel_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_webengine.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_webengine_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecore.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecore_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_webenginewidgets.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_websockets.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_websockets_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_webview.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_webview_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_widgets.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_widgets_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_winextras.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_winextras_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_xml.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_xml_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_xmlpatterns.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_zlib_private.pri \
		F:\QT5.7\5.7\msvc2015\mkspecs\features\qt_functions.prf \
		F:\QT5.7\5.7\msvc2015\mkspecs\features\qt_config.prf \
		F:\QT5.7\5.7\msvc2015\mkspecs\features\win32\qt_config.prf \
		F:\QT5.7\5.7\msvc2015\mkspecs\win32-msvc2015\qmake.conf \
		F:\QT5.7\5.7\msvc2015\mkspecs\features\spec_post.prf \
		F:\QT5.7\5.7\msvc2015\mkspecs\features\exclusive_builds.prf \
		F:\QT5.7\5.7\msvc2015\mkspecs\features\toolchain.prf \
		F:\QT5.7\5.7\msvc2015\mkspecs\features\default_pre.prf \
		F:\QT5.7\5.7\msvc2015\mkspecs\features\win32\default_pre.prf \
		F:\QT5.7\5.7\msvc2015\mkspecs\features\resolve_config.prf \
		F:\QT5.7\5.7\msvc2015\mkspecs\features\exclusive_builds_post.prf \
		F:\QT5.7\5.7\msvc2015\mkspecs\features\default_post.prf \
		F:\QT5.7\5.7\msvc2015\mkspecs\features\win32\rtti.prf \
		F:\QT5.7\5.7\msvc2015\mkspecs\features\precompile_header.prf \
		F:\QT5.7\5.7\msvc2015\mkspecs\features\warn_on.prf \
		F:\QT5.7\5.7\msvc2015\mkspecs\features\file_copies.prf \
		F:\QT5.7\5.7\msvc2015\mkspecs\features\win32\windows.prf \
		F:\QT5.7\5.7\msvc2015\mkspecs\features\testcase_targets.prf \
		F:\QT5.7\5.7\msvc2015\mkspecs\features\exceptions.prf \
		F:\QT5.7\5.7\msvc2015\mkspecs\features\yacc.prf \
		F:\QT5.7\5.7\msvc2015\mkspecs\features\lex.prf \
		BlsNetPlatformPro.pro
	$(QMAKE) -spec win32-msvc2015 -o Makefile BlsNetPlatformPro.pro
F:\QT5.7\5.7\msvc2015\mkspecs\features\spec_pre.prf:
F:\QT5.7\5.7\msvc2015\mkspecs\common\angle.conf:
F:\QT5.7\5.7\msvc2015\mkspecs\common\msvc-base.conf:
F:\QT5.7\5.7\msvc2015\mkspecs\common\msvc-desktop.conf:
F:\QT5.7\5.7\msvc2015\mkspecs\qconfig.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dcore.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dcore_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dextras.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dextras_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dinput.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dinput_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dlogic.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dlogic_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dquick.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dquick_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickextras.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickextras_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickinput.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickinput_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickrender.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickrender_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3drender.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_3drender_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_axbase.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_axbase_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_axcontainer.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_axcontainer_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_axserver.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_axserver_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_bluetooth.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_bluetooth_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_bootstrap_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_charts.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_charts_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_clucene_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_concurrent.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_concurrent_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_core.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_core_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_dbus.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_dbus_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_designer.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_designer_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_designercomponents_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_gamepad.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_gamepad_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_gui.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_gui_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_help.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_help_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_location.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_location_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_multimedia.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_multimedia_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_multimediawidgets.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_network.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_network_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_nfc.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_nfc_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_opengl.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_opengl_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_openglextensions.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_openglextensions_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_packetprotocol_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_platformsupport_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_positioning.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_positioning_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_printsupport.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_printsupport_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_purchasing.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_purchasing_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_qml.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_qml_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_qmldebug_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_qmldevtools_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_qmltest.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_qmltest_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_quick.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_quick_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_quickcontrols2.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_quickparticles_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_quickwidgets.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_quickwidgets_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_script.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_script_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_scripttools.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_scripttools_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_scxml.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_scxml_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_sensors.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_sensors_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_serialbus.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_serialbus_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_serialport.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_serialport_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_sql.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_sql_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_svg.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_svg_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_testlib.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_testlib_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_uiplugin.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_uitools.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_uitools_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_webchannel.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_webchannel_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_webengine.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_webengine_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecore.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecore_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_webenginewidgets.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_websockets.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_websockets_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_webview.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_webview_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_widgets.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_widgets_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_winextras.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_winextras_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_xml.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_xml_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_xmlpatterns.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\modules\qt_lib_zlib_private.pri:
F:\QT5.7\5.7\msvc2015\mkspecs\features\qt_functions.prf:
F:\QT5.7\5.7\msvc2015\mkspecs\features\qt_config.prf:
F:\QT5.7\5.7\msvc2015\mkspecs\features\win32\qt_config.prf:
F:\QT5.7\5.7\msvc2015\mkspecs\win32-msvc2015\qmake.conf:
F:\QT5.7\5.7\msvc2015\mkspecs\features\spec_post.prf:
F:\QT5.7\5.7\msvc2015\mkspecs\features\exclusive_builds.prf:
F:\QT5.7\5.7\msvc2015\mkspecs\features\toolchain.prf:
F:\QT5.7\5.7\msvc2015\mkspecs\features\default_pre.prf:
F:\QT5.7\5.7\msvc2015\mkspecs\features\win32\default_pre.prf:
F:\QT5.7\5.7\msvc2015\mkspecs\features\resolve_config.prf:
F:\QT5.7\5.7\msvc2015\mkspecs\features\exclusive_builds_post.prf:
F:\QT5.7\5.7\msvc2015\mkspecs\features\default_post.prf:
F:\QT5.7\5.7\msvc2015\mkspecs\features\win32\rtti.prf:
F:\QT5.7\5.7\msvc2015\mkspecs\features\precompile_header.prf:
F:\QT5.7\5.7\msvc2015\mkspecs\features\warn_on.prf:
F:\QT5.7\5.7\msvc2015\mkspecs\features\file_copies.prf:
F:\QT5.7\5.7\msvc2015\mkspecs\features\win32\windows.prf:
F:\QT5.7\5.7\msvc2015\mkspecs\features\testcase_targets.prf:
F:\QT5.7\5.7\msvc2015\mkspecs\features\exceptions.prf:
F:\QT5.7\5.7\msvc2015\mkspecs\features\yacc.prf:
F:\QT5.7\5.7\msvc2015\mkspecs\features\lex.prf:
BlsNetPlatformPro.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2015 -o Makefile BlsNetPlatformPro.pro

qmake_all: sub-E--CPRGit-UI-UI-pro-qmake_all FORCE

make_first: sub-E--CPRGit-UI-UI-pro-make_first  FORCE
all: sub-E--CPRGit-UI-UI-pro-all  FORCE
clean: sub-E--CPRGit-UI-UI-pro-clean  FORCE
distclean: sub-E--CPRGit-UI-UI-pro-distclean  FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-E--CPRGit-UI-UI-pro-install_subtargets FORCE
uninstall_subtargets: sub-E--CPRGit-UI-UI-pro-uninstall_subtargets FORCE

sub-E--CPRGit-UI-UI-pro-debug:
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && ( if not exist Makefile $(QMAKE) E:\CPRGit\UI\UI.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-E--CPRGit-UI-UI-pro-debug

sub-E--CPRGit-UI-UI-pro-release:
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && ( if not exist Makefile $(QMAKE) E:\CPRGit\UI\UI.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile release
release: sub-E--CPRGit-UI-UI-pro-release

sub-E--CPRGit-UI-UI-pro-check:
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && ( if not exist Makefile $(QMAKE) E:\CPRGit\UI\UI.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile check
check: sub-E--CPRGit-UI-UI-pro-check

sub-E--CPRGit-UI-UI-pro-benchmark:
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && ( if not exist Makefile $(QMAKE) E:\CPRGit\UI\UI.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile benchmark
benchmark: sub-E--CPRGit-UI-UI-pro-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

