#############################################################################
# Makefile for building: BlsNetPlatformPro
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  BlsNetPlatformPro.pro
# Template: subdirs
# Command: F:\QT5.7.1\5.7\msvc2015\bin\qmake.exe -spec win32-msvc2015 -o Makefile BlsNetPlatformPro.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = F:\QT5.7.1\5.7\msvc2015\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-E--BlsNetPlatformPro-UI-UI-pro \
		sub-adultParams \
		sub-simulatorEmulateBuild \
		sub-physiologyWatchBar \
		sub-simulatorSymptom \
		sub-scriptFlowEngine \
		sub-E--BlsNetPlatformPro-common-common-pro \
		sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro \
		sub-E--BlsNetPlatformPro-elementParse-elementParse-pro \
		sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro \
		sub-E--BlsNetPlatformPro-transLayer-transLayer-pro \
		sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro


sub-E--BlsNetPlatformPro-UI-UI-pro-qmake_all:  FORCE
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	cd UI\ && $(QMAKE) E:\BlsNetPlatformPro\UI\UI.pro -spec win32-msvc2015 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && $(MAKE) -f Makefile qmake_all
sub-E--BlsNetPlatformPro-UI-UI-pro: FORCE
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\UI\UI.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile
sub-E--BlsNetPlatformPro-UI-UI-pro-make_first: FORCE
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\UI\UI.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile 
sub-E--BlsNetPlatformPro-UI-UI-pro-all: FORCE
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\UI\UI.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile all
sub-E--BlsNetPlatformPro-UI-UI-pro-clean: FORCE
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\UI\UI.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile clean
sub-E--BlsNetPlatformPro-UI-UI-pro-distclean: FORCE
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\UI\UI.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-E--BlsNetPlatformPro-UI-UI-pro-install_subtargets: FORCE
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\UI\UI.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile install
sub-E--BlsNetPlatformPro-UI-UI-pro-uninstall_subtargets: FORCE
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\UI\UI.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-adultParams-qmake_all:  FORCE
	@if not exist adultParams\ mkdir adultParams\ & if not exist adultParams\ exit 1
	cd adultParams\ && $(QMAKE) E:\BlsNetPlatformPro\adultParams\adultParams.pro -spec win32-msvc2015 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd adultParams\ && $(MAKE) -f Makefile qmake_all
sub-adultParams: FORCE
	@if not exist adultParams\ mkdir adultParams\ & if not exist adultParams\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd adultParams\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\adultParams\adultParams.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile
sub-adultParams-make_first: FORCE
	@if not exist adultParams\ mkdir adultParams\ & if not exist adultParams\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd adultParams\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\adultParams\adultParams.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile 
sub-adultParams-all: FORCE
	@if not exist adultParams\ mkdir adultParams\ & if not exist adultParams\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd adultParams\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\adultParams\adultParams.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile all
sub-adultParams-clean: FORCE
	@if not exist adultParams\ mkdir adultParams\ & if not exist adultParams\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd adultParams\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\adultParams\adultParams.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile clean
sub-adultParams-distclean: FORCE
	@if not exist adultParams\ mkdir adultParams\ & if not exist adultParams\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd adultParams\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\adultParams\adultParams.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-adultParams-install_subtargets: FORCE
	@if not exist adultParams\ mkdir adultParams\ & if not exist adultParams\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd adultParams\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\adultParams\adultParams.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile install
sub-adultParams-uninstall_subtargets: FORCE
	@if not exist adultParams\ mkdir adultParams\ & if not exist adultParams\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd adultParams\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\adultParams\adultParams.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-simulatorEmulateBuild-qmake_all:  FORCE
	@if not exist simulatorEmulateBuild\ mkdir simulatorEmulateBuild\ & if not exist simulatorEmulateBuild\ exit 1
	cd simulatorEmulateBuild\ && $(QMAKE) E:\BlsNetPlatformPro\simulatorEmulateBuild\simulatorEmulateBuild.pro -spec win32-msvc2015 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorEmulateBuild\ && $(MAKE) -f Makefile qmake_all
sub-simulatorEmulateBuild: FORCE
	@if not exist simulatorEmulateBuild\ mkdir simulatorEmulateBuild\ & if not exist simulatorEmulateBuild\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorEmulateBuild\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorEmulateBuild\simulatorEmulateBuild.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile
sub-simulatorEmulateBuild-make_first: FORCE
	@if not exist simulatorEmulateBuild\ mkdir simulatorEmulateBuild\ & if not exist simulatorEmulateBuild\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorEmulateBuild\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorEmulateBuild\simulatorEmulateBuild.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile 
sub-simulatorEmulateBuild-all: FORCE
	@if not exist simulatorEmulateBuild\ mkdir simulatorEmulateBuild\ & if not exist simulatorEmulateBuild\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorEmulateBuild\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorEmulateBuild\simulatorEmulateBuild.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile all
sub-simulatorEmulateBuild-clean: FORCE
	@if not exist simulatorEmulateBuild\ mkdir simulatorEmulateBuild\ & if not exist simulatorEmulateBuild\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorEmulateBuild\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorEmulateBuild\simulatorEmulateBuild.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile clean
sub-simulatorEmulateBuild-distclean: FORCE
	@if not exist simulatorEmulateBuild\ mkdir simulatorEmulateBuild\ & if not exist simulatorEmulateBuild\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorEmulateBuild\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorEmulateBuild\simulatorEmulateBuild.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-simulatorEmulateBuild-install_subtargets: FORCE
	@if not exist simulatorEmulateBuild\ mkdir simulatorEmulateBuild\ & if not exist simulatorEmulateBuild\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorEmulateBuild\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorEmulateBuild\simulatorEmulateBuild.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile install
sub-simulatorEmulateBuild-uninstall_subtargets: FORCE
	@if not exist simulatorEmulateBuild\ mkdir simulatorEmulateBuild\ & if not exist simulatorEmulateBuild\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorEmulateBuild\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorEmulateBuild\simulatorEmulateBuild.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-physiologyWatchBar-qmake_all:  FORCE
	@if not exist physiologyWatchBar\ mkdir physiologyWatchBar\ & if not exist physiologyWatchBar\ exit 1
	cd physiologyWatchBar\ && $(QMAKE) E:\BlsNetPlatformPro\physiologyWatchBar\physiologyWatchBar.pro -spec win32-msvc2015 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd physiologyWatchBar\ && $(MAKE) -f Makefile qmake_all
sub-physiologyWatchBar: FORCE
	@if not exist physiologyWatchBar\ mkdir physiologyWatchBar\ & if not exist physiologyWatchBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd physiologyWatchBar\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\physiologyWatchBar\physiologyWatchBar.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile
sub-physiologyWatchBar-make_first: FORCE
	@if not exist physiologyWatchBar\ mkdir physiologyWatchBar\ & if not exist physiologyWatchBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd physiologyWatchBar\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\physiologyWatchBar\physiologyWatchBar.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile 
sub-physiologyWatchBar-all: FORCE
	@if not exist physiologyWatchBar\ mkdir physiologyWatchBar\ & if not exist physiologyWatchBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd physiologyWatchBar\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\physiologyWatchBar\physiologyWatchBar.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile all
sub-physiologyWatchBar-clean: FORCE
	@if not exist physiologyWatchBar\ mkdir physiologyWatchBar\ & if not exist physiologyWatchBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd physiologyWatchBar\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\physiologyWatchBar\physiologyWatchBar.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile clean
sub-physiologyWatchBar-distclean: FORCE
	@if not exist physiologyWatchBar\ mkdir physiologyWatchBar\ & if not exist physiologyWatchBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd physiologyWatchBar\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\physiologyWatchBar\physiologyWatchBar.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-physiologyWatchBar-install_subtargets: FORCE
	@if not exist physiologyWatchBar\ mkdir physiologyWatchBar\ & if not exist physiologyWatchBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd physiologyWatchBar\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\physiologyWatchBar\physiologyWatchBar.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile install
sub-physiologyWatchBar-uninstall_subtargets: FORCE
	@if not exist physiologyWatchBar\ mkdir physiologyWatchBar\ & if not exist physiologyWatchBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd physiologyWatchBar\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\physiologyWatchBar\physiologyWatchBar.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-simulatorSymptom-qmake_all:  FORCE
	@if not exist simulatorSymptom\ mkdir simulatorSymptom\ & if not exist simulatorSymptom\ exit 1
	cd simulatorSymptom\ && $(QMAKE) E:\BlsNetPlatformPro\simulatorSymptom\simulatorSymptom.pro -spec win32-msvc2015 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorSymptom\ && $(MAKE) -f Makefile qmake_all
sub-simulatorSymptom: FORCE
	@if not exist simulatorSymptom\ mkdir simulatorSymptom\ & if not exist simulatorSymptom\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorSymptom\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorSymptom\simulatorSymptom.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile
sub-simulatorSymptom-make_first: FORCE
	@if not exist simulatorSymptom\ mkdir simulatorSymptom\ & if not exist simulatorSymptom\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorSymptom\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorSymptom\simulatorSymptom.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile 
sub-simulatorSymptom-all: FORCE
	@if not exist simulatorSymptom\ mkdir simulatorSymptom\ & if not exist simulatorSymptom\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorSymptom\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorSymptom\simulatorSymptom.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile all
sub-simulatorSymptom-clean: FORCE
	@if not exist simulatorSymptom\ mkdir simulatorSymptom\ & if not exist simulatorSymptom\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorSymptom\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorSymptom\simulatorSymptom.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile clean
sub-simulatorSymptom-distclean: FORCE
	@if not exist simulatorSymptom\ mkdir simulatorSymptom\ & if not exist simulatorSymptom\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorSymptom\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorSymptom\simulatorSymptom.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-simulatorSymptom-install_subtargets: FORCE
	@if not exist simulatorSymptom\ mkdir simulatorSymptom\ & if not exist simulatorSymptom\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorSymptom\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorSymptom\simulatorSymptom.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile install
sub-simulatorSymptom-uninstall_subtargets: FORCE
	@if not exist simulatorSymptom\ mkdir simulatorSymptom\ & if not exist simulatorSymptom\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorSymptom\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorSymptom\simulatorSymptom.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-scriptFlowEngine-qmake_all:  FORCE
	@if not exist scriptFlowEngine\ mkdir scriptFlowEngine\ & if not exist scriptFlowEngine\ exit 1
	cd scriptFlowEngine\ && $(QMAKE) E:\BlsNetPlatformPro\scriptFlowEngine\scriptFlowEngine.pro -spec win32-msvc2015 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd scriptFlowEngine\ && $(MAKE) -f Makefile qmake_all
sub-scriptFlowEngine: FORCE
	@if not exist scriptFlowEngine\ mkdir scriptFlowEngine\ & if not exist scriptFlowEngine\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd scriptFlowEngine\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\scriptFlowEngine\scriptFlowEngine.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile
sub-scriptFlowEngine-make_first: FORCE
	@if not exist scriptFlowEngine\ mkdir scriptFlowEngine\ & if not exist scriptFlowEngine\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd scriptFlowEngine\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\scriptFlowEngine\scriptFlowEngine.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile 
sub-scriptFlowEngine-all: FORCE
	@if not exist scriptFlowEngine\ mkdir scriptFlowEngine\ & if not exist scriptFlowEngine\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd scriptFlowEngine\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\scriptFlowEngine\scriptFlowEngine.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile all
sub-scriptFlowEngine-clean: FORCE
	@if not exist scriptFlowEngine\ mkdir scriptFlowEngine\ & if not exist scriptFlowEngine\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd scriptFlowEngine\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\scriptFlowEngine\scriptFlowEngine.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile clean
sub-scriptFlowEngine-distclean: FORCE
	@if not exist scriptFlowEngine\ mkdir scriptFlowEngine\ & if not exist scriptFlowEngine\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd scriptFlowEngine\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\scriptFlowEngine\scriptFlowEngine.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-scriptFlowEngine-install_subtargets: FORCE
	@if not exist scriptFlowEngine\ mkdir scriptFlowEngine\ & if not exist scriptFlowEngine\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd scriptFlowEngine\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\scriptFlowEngine\scriptFlowEngine.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile install
sub-scriptFlowEngine-uninstall_subtargets: FORCE
	@if not exist scriptFlowEngine\ mkdir scriptFlowEngine\ & if not exist scriptFlowEngine\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd scriptFlowEngine\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\scriptFlowEngine\scriptFlowEngine.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-E--BlsNetPlatformPro-common-common-pro-qmake_all:  FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && $(QMAKE) E:\BlsNetPlatformPro\common\common.pro -spec win32-msvc2015 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && $(MAKE) -f Makefile qmake_all
sub-E--BlsNetPlatformPro-common-common-pro: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\common\common.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile
sub-E--BlsNetPlatformPro-common-common-pro-make_first: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\common\common.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile 
sub-E--BlsNetPlatformPro-common-common-pro-all: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\common\common.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile all
sub-E--BlsNetPlatformPro-common-common-pro-clean: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\common\common.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile clean
sub-E--BlsNetPlatformPro-common-common-pro-distclean: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\common\common.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-E--BlsNetPlatformPro-common-common-pro-install_subtargets: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\common\common.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile install
sub-E--BlsNetPlatformPro-common-common-pro-uninstall_subtargets: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\common\common.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro-qmake_all:  FORCE
	@if not exist cprModuls\ mkdir cprModuls\ & if not exist cprModuls\ exit 1
	cd cprModuls\ && $(QMAKE) E:\BlsNetPlatformPro\cprModuls\cprModuls.pro -spec win32-msvc2015 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cprModuls\ && $(MAKE) -f Makefile qmake_all
sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro: FORCE
	@if not exist cprModuls\ mkdir cprModuls\ & if not exist cprModuls\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cprModuls\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\cprModuls\cprModuls.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile
sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro-make_first: FORCE
	@if not exist cprModuls\ mkdir cprModuls\ & if not exist cprModuls\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cprModuls\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\cprModuls\cprModuls.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile 
sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro-all: FORCE
	@if not exist cprModuls\ mkdir cprModuls\ & if not exist cprModuls\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cprModuls\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\cprModuls\cprModuls.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile all
sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro-clean: FORCE
	@if not exist cprModuls\ mkdir cprModuls\ & if not exist cprModuls\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cprModuls\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\cprModuls\cprModuls.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile clean
sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro-distclean: FORCE
	@if not exist cprModuls\ mkdir cprModuls\ & if not exist cprModuls\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cprModuls\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\cprModuls\cprModuls.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro-install_subtargets: FORCE
	@if not exist cprModuls\ mkdir cprModuls\ & if not exist cprModuls\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cprModuls\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\cprModuls\cprModuls.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile install
sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro-uninstall_subtargets: FORCE
	@if not exist cprModuls\ mkdir cprModuls\ & if not exist cprModuls\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cprModuls\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\cprModuls\cprModuls.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-E--BlsNetPlatformPro-elementParse-elementParse-pro-qmake_all:  FORCE
	@if not exist elementParse\ mkdir elementParse\ & if not exist elementParse\ exit 1
	cd elementParse\ && $(QMAKE) E:\BlsNetPlatformPro\elementParse\elementParse.pro -spec win32-msvc2015 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd elementParse\ && $(MAKE) -f Makefile qmake_all
sub-E--BlsNetPlatformPro-elementParse-elementParse-pro: FORCE
	@if not exist elementParse\ mkdir elementParse\ & if not exist elementParse\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd elementParse\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\elementParse\elementParse.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile
sub-E--BlsNetPlatformPro-elementParse-elementParse-pro-make_first: FORCE
	@if not exist elementParse\ mkdir elementParse\ & if not exist elementParse\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd elementParse\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\elementParse\elementParse.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile 
sub-E--BlsNetPlatformPro-elementParse-elementParse-pro-all: FORCE
	@if not exist elementParse\ mkdir elementParse\ & if not exist elementParse\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd elementParse\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\elementParse\elementParse.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile all
sub-E--BlsNetPlatformPro-elementParse-elementParse-pro-clean: FORCE
	@if not exist elementParse\ mkdir elementParse\ & if not exist elementParse\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd elementParse\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\elementParse\elementParse.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile clean
sub-E--BlsNetPlatformPro-elementParse-elementParse-pro-distclean: FORCE
	@if not exist elementParse\ mkdir elementParse\ & if not exist elementParse\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd elementParse\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\elementParse\elementParse.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-E--BlsNetPlatformPro-elementParse-elementParse-pro-install_subtargets: FORCE
	@if not exist elementParse\ mkdir elementParse\ & if not exist elementParse\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd elementParse\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\elementParse\elementParse.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile install
sub-E--BlsNetPlatformPro-elementParse-elementParse-pro-uninstall_subtargets: FORCE
	@if not exist elementParse\ mkdir elementParse\ & if not exist elementParse\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd elementParse\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\elementParse\elementParse.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro-qmake_all:  FORCE
	@if not exist simulatorBase\ mkdir simulatorBase\ & if not exist simulatorBase\ exit 1
	cd simulatorBase\ && $(QMAKE) E:\BlsNetPlatformPro\simulatorBase\simulatorBase.pro -spec win32-msvc2015 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorBase\ && $(MAKE) -f Makefile qmake_all
sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro: FORCE
	@if not exist simulatorBase\ mkdir simulatorBase\ & if not exist simulatorBase\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorBase\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorBase\simulatorBase.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile
sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro-make_first: FORCE
	@if not exist simulatorBase\ mkdir simulatorBase\ & if not exist simulatorBase\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorBase\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorBase\simulatorBase.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile 
sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro-all: FORCE
	@if not exist simulatorBase\ mkdir simulatorBase\ & if not exist simulatorBase\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorBase\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorBase\simulatorBase.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile all
sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro-clean: FORCE
	@if not exist simulatorBase\ mkdir simulatorBase\ & if not exist simulatorBase\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorBase\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorBase\simulatorBase.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile clean
sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro-distclean: FORCE
	@if not exist simulatorBase\ mkdir simulatorBase\ & if not exist simulatorBase\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorBase\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorBase\simulatorBase.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro-install_subtargets: FORCE
	@if not exist simulatorBase\ mkdir simulatorBase\ & if not exist simulatorBase\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorBase\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorBase\simulatorBase.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile install
sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro-uninstall_subtargets: FORCE
	@if not exist simulatorBase\ mkdir simulatorBase\ & if not exist simulatorBase\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorBase\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorBase\simulatorBase.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-E--BlsNetPlatformPro-transLayer-transLayer-pro-qmake_all:  FORCE
	@if not exist transLayer\ mkdir transLayer\ & if not exist transLayer\ exit 1
	cd transLayer\ && $(QMAKE) E:\BlsNetPlatformPro\transLayer\transLayer.pro -spec win32-msvc2015 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd transLayer\ && $(MAKE) -f Makefile qmake_all
sub-E--BlsNetPlatformPro-transLayer-transLayer-pro: FORCE
	@if not exist transLayer\ mkdir transLayer\ & if not exist transLayer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd transLayer\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\transLayer\transLayer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile
sub-E--BlsNetPlatformPro-transLayer-transLayer-pro-make_first: FORCE
	@if not exist transLayer\ mkdir transLayer\ & if not exist transLayer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd transLayer\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\transLayer\transLayer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile 
sub-E--BlsNetPlatformPro-transLayer-transLayer-pro-all: FORCE
	@if not exist transLayer\ mkdir transLayer\ & if not exist transLayer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd transLayer\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\transLayer\transLayer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile all
sub-E--BlsNetPlatformPro-transLayer-transLayer-pro-clean: FORCE
	@if not exist transLayer\ mkdir transLayer\ & if not exist transLayer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd transLayer\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\transLayer\transLayer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile clean
sub-E--BlsNetPlatformPro-transLayer-transLayer-pro-distclean: FORCE
	@if not exist transLayer\ mkdir transLayer\ & if not exist transLayer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd transLayer\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\transLayer\transLayer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-E--BlsNetPlatformPro-transLayer-transLayer-pro-install_subtargets: FORCE
	@if not exist transLayer\ mkdir transLayer\ & if not exist transLayer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd transLayer\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\transLayer\transLayer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile install
sub-E--BlsNetPlatformPro-transLayer-transLayer-pro-uninstall_subtargets: FORCE
	@if not exist transLayer\ mkdir transLayer\ & if not exist transLayer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd transLayer\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\transLayer\transLayer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro-qmake_all:  FORCE
	@if not exist BlsUintTest\ mkdir BlsUintTest\ & if not exist BlsUintTest\ exit 1
	cd BlsUintTest\ && $(QMAKE) E:\BlsNetPlatformPro\BlsUintTest\BlsUintTest.pro -spec win32-msvc2015 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BlsUintTest\ && $(MAKE) -f Makefile qmake_all
sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro: FORCE
	@if not exist BlsUintTest\ mkdir BlsUintTest\ & if not exist BlsUintTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BlsUintTest\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\BlsUintTest\BlsUintTest.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile
sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro-make_first: FORCE
	@if not exist BlsUintTest\ mkdir BlsUintTest\ & if not exist BlsUintTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BlsUintTest\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\BlsUintTest\BlsUintTest.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile 
sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro-all: FORCE
	@if not exist BlsUintTest\ mkdir BlsUintTest\ & if not exist BlsUintTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BlsUintTest\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\BlsUintTest\BlsUintTest.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile all
sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro-clean: FORCE
	@if not exist BlsUintTest\ mkdir BlsUintTest\ & if not exist BlsUintTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BlsUintTest\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\BlsUintTest\BlsUintTest.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile clean
sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro-distclean: FORCE
	@if not exist BlsUintTest\ mkdir BlsUintTest\ & if not exist BlsUintTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BlsUintTest\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\BlsUintTest\BlsUintTest.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro-install_subtargets: FORCE
	@if not exist BlsUintTest\ mkdir BlsUintTest\ & if not exist BlsUintTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BlsUintTest\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\BlsUintTest\BlsUintTest.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile install
sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro-uninstall_subtargets: FORCE
	@if not exist BlsUintTest\ mkdir BlsUintTest\ & if not exist BlsUintTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BlsUintTest\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\BlsUintTest\BlsUintTest.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: BlsNetPlatformPro.pro F:\QT5.7.1\5.7\msvc2015\mkspecs\win32-msvc2015\qmake.conf F:\QT5.7.1\5.7\msvc2015\mkspecs\features\spec_pre.prf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\common\angle.conf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\common\msvc-base.conf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\common\msvc-desktop.conf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\qconfig.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dcore.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dcore_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dextras.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dextras_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dinput.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dinput_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dlogic.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dlogic_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dquick.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dquick_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickextras.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickinput.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickrender.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3drender.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3drender_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_axbase.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_axbase_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_axcontainer.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_axcontainer_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_axserver.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_axserver_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_bluetooth.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_bluetooth_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_bootstrap_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_charts.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_charts_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_clucene_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_concurrent.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_concurrent_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_core.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_core_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_dbus.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_dbus_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_designer.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_designer_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_designercomponents_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_gamepad.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_gamepad_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_gui.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_gui_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_help.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_help_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_location.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_location_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_multimedia.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_multimedia_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_multimediawidgets.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_network.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_network_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_nfc.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_nfc_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_opengl.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_opengl_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_openglextensions.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_openglextensions_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_platformsupport_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_positioning.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_positioning_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_printsupport.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_printsupport_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_purchasing.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_purchasing_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_qml.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_qml_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_qmldebug_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_qmltest.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_qmltest_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_quick.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_quick_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_quickcontrols2.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_quickparticles_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_quickwidgets.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_script.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_script_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_scripttools.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_scripttools_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_scxml.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_scxml_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_sensors.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_sensors_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_serialbus.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_serialbus_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_serialport.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_serialport_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_sql.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_sql_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_svg.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_svg_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_testlib.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_testlib_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_uiplugin.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_uitools.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_uitools_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_webchannel.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_webchannel_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_webengine.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_webengine_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecore.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecore_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_webenginewidgets.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_websockets.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_websockets_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_webview.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_webview_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_widgets.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_widgets_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_winextras.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_winextras_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_xml.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_xml_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_xmlpatterns.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_zlib_private.pri \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\features\qt_functions.prf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\features\qt_config.prf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\features\win32\qt_config.prf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\win32-msvc2015\qmake.conf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\features\spec_post.prf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\features\exclusive_builds.prf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\features\toolchain.prf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\features\default_pre.prf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\features\win32\default_pre.prf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\features\resolve_config.prf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\features\exclusive_builds_post.prf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\features\default_post.prf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\features\win32\rtti.prf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\features\precompile_header.prf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\features\warn_on.prf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\features\file_copies.prf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\features\win32\windows.prf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\features\testcase_targets.prf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\features\exceptions.prf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\features\yacc.prf \
		F:\QT5.7.1\5.7\msvc2015\mkspecs\features\lex.prf \
		BlsNetPlatformPro.pro
	$(QMAKE) -spec win32-msvc2015 -o Makefile BlsNetPlatformPro.pro
F:\QT5.7.1\5.7\msvc2015\mkspecs\features\spec_pre.prf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\common\angle.conf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\common\msvc-base.conf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\common\msvc-desktop.conf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\qconfig.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dcore.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dcore_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dextras.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dextras_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dinput.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dinput_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dlogic.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dlogic_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dquick.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dquick_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickextras.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickextras_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickinput.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickinput_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickrender.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3dquickrender_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3drender.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_3drender_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_axbase.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_axbase_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_axcontainer.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_axcontainer_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_axserver.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_axserver_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_bluetooth.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_bluetooth_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_bootstrap_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_charts.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_charts_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_clucene_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_concurrent.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_concurrent_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_core.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_core_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_dbus.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_dbus_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_designer.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_designer_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_designercomponents_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_gamepad.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_gamepad_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_gui.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_gui_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_help.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_help_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_location.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_location_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_multimedia.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_multimedia_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_multimediawidgets.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_network.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_network_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_nfc.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_nfc_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_opengl.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_opengl_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_openglextensions.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_openglextensions_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_packetprotocol_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_platformsupport_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_positioning.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_positioning_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_printsupport.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_printsupport_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_purchasing.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_purchasing_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_qml.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_qml_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_qmldebug_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_qmldevtools_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_qmltest.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_qmltest_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_quick.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_quick_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_quickcontrols2.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_quickparticles_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_quickwidgets.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_quickwidgets_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_script.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_script_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_scripttools.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_scripttools_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_scxml.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_scxml_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_sensors.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_sensors_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_serialbus.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_serialbus_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_serialport.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_serialport_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_sql.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_sql_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_svg.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_svg_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_testlib.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_testlib_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_uiplugin.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_uitools.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_uitools_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_webchannel.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_webchannel_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_webengine.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_webengine_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecore.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecore_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_webenginewidgets.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_websockets.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_websockets_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_webview.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_webview_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_widgets.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_widgets_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_winextras.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_winextras_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_xml.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_xml_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_xmlpatterns.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\modules\qt_lib_zlib_private.pri:
F:\QT5.7.1\5.7\msvc2015\mkspecs\features\qt_functions.prf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\features\qt_config.prf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\features\win32\qt_config.prf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\win32-msvc2015\qmake.conf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\features\spec_post.prf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\features\exclusive_builds.prf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\features\toolchain.prf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\features\default_pre.prf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\features\win32\default_pre.prf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\features\resolve_config.prf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\features\exclusive_builds_post.prf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\features\default_post.prf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\features\win32\rtti.prf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\features\precompile_header.prf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\features\warn_on.prf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\features\file_copies.prf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\features\win32\windows.prf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\features\testcase_targets.prf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\features\exceptions.prf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\features\yacc.prf:
F:\QT5.7.1\5.7\msvc2015\mkspecs\features\lex.prf:
BlsNetPlatformPro.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2015 -o Makefile BlsNetPlatformPro.pro

qmake_all: sub-E--BlsNetPlatformPro-UI-UI-pro-qmake_all sub-adultParams-qmake_all sub-simulatorEmulateBuild-qmake_all sub-physiologyWatchBar-qmake_all sub-simulatorSymptom-qmake_all sub-scriptFlowEngine-qmake_all sub-E--BlsNetPlatformPro-common-common-pro-qmake_all sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro-qmake_all sub-E--BlsNetPlatformPro-elementParse-elementParse-pro-qmake_all sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro-qmake_all sub-E--BlsNetPlatformPro-transLayer-transLayer-pro-qmake_all sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro-qmake_all FORCE

make_first: sub-E--BlsNetPlatformPro-UI-UI-pro-make_first sub-adultParams-make_first sub-simulatorEmulateBuild-make_first sub-physiologyWatchBar-make_first sub-simulatorSymptom-make_first sub-scriptFlowEngine-make_first sub-E--BlsNetPlatformPro-common-common-pro-make_first sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro-make_first sub-E--BlsNetPlatformPro-elementParse-elementParse-pro-make_first sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro-make_first sub-E--BlsNetPlatformPro-transLayer-transLayer-pro-make_first sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro-make_first  FORCE
all: sub-E--BlsNetPlatformPro-UI-UI-pro-all sub-adultParams-all sub-simulatorEmulateBuild-all sub-physiologyWatchBar-all sub-simulatorSymptom-all sub-scriptFlowEngine-all sub-E--BlsNetPlatformPro-common-common-pro-all sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro-all sub-E--BlsNetPlatformPro-elementParse-elementParse-pro-all sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro-all sub-E--BlsNetPlatformPro-transLayer-transLayer-pro-all sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro-all  FORCE
clean: sub-E--BlsNetPlatformPro-UI-UI-pro-clean sub-adultParams-clean sub-simulatorEmulateBuild-clean sub-physiologyWatchBar-clean sub-simulatorSymptom-clean sub-scriptFlowEngine-clean sub-E--BlsNetPlatformPro-common-common-pro-clean sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro-clean sub-E--BlsNetPlatformPro-elementParse-elementParse-pro-clean sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro-clean sub-E--BlsNetPlatformPro-transLayer-transLayer-pro-clean sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro-clean  FORCE
distclean: sub-E--BlsNetPlatformPro-UI-UI-pro-distclean sub-adultParams-distclean sub-simulatorEmulateBuild-distclean sub-physiologyWatchBar-distclean sub-simulatorSymptom-distclean sub-scriptFlowEngine-distclean sub-E--BlsNetPlatformPro-common-common-pro-distclean sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro-distclean sub-E--BlsNetPlatformPro-elementParse-elementParse-pro-distclean sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro-distclean sub-E--BlsNetPlatformPro-transLayer-transLayer-pro-distclean sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro-distclean  FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-E--BlsNetPlatformPro-UI-UI-pro-install_subtargets sub-adultParams-install_subtargets sub-simulatorEmulateBuild-install_subtargets sub-physiologyWatchBar-install_subtargets sub-simulatorSymptom-install_subtargets sub-scriptFlowEngine-install_subtargets sub-E--BlsNetPlatformPro-common-common-pro-install_subtargets sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro-install_subtargets sub-E--BlsNetPlatformPro-elementParse-elementParse-pro-install_subtargets sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro-install_subtargets sub-E--BlsNetPlatformPro-transLayer-transLayer-pro-install_subtargets sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro-install_subtargets FORCE
uninstall_subtargets: sub-E--BlsNetPlatformPro-UI-UI-pro-uninstall_subtargets sub-adultParams-uninstall_subtargets sub-simulatorEmulateBuild-uninstall_subtargets sub-physiologyWatchBar-uninstall_subtargets sub-simulatorSymptom-uninstall_subtargets sub-scriptFlowEngine-uninstall_subtargets sub-E--BlsNetPlatformPro-common-common-pro-uninstall_subtargets sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro-uninstall_subtargets sub-E--BlsNetPlatformPro-elementParse-elementParse-pro-uninstall_subtargets sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro-uninstall_subtargets sub-E--BlsNetPlatformPro-transLayer-transLayer-pro-uninstall_subtargets sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro-uninstall_subtargets FORCE

sub-E--BlsNetPlatformPro-UI-UI-pro-debug:
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\UI\UI.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile debug
sub-adultParams-debug:
	@if not exist adultParams\ mkdir adultParams\ & if not exist adultParams\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd adultParams\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\adultParams\adultParams.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile debug
sub-simulatorEmulateBuild-debug:
	@if not exist simulatorEmulateBuild\ mkdir simulatorEmulateBuild\ & if not exist simulatorEmulateBuild\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorEmulateBuild\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorEmulateBuild\simulatorEmulateBuild.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile debug
sub-physiologyWatchBar-debug:
	@if not exist physiologyWatchBar\ mkdir physiologyWatchBar\ & if not exist physiologyWatchBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd physiologyWatchBar\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\physiologyWatchBar\physiologyWatchBar.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile debug
sub-simulatorSymptom-debug:
	@if not exist simulatorSymptom\ mkdir simulatorSymptom\ & if not exist simulatorSymptom\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorSymptom\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorSymptom\simulatorSymptom.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile debug
sub-scriptFlowEngine-debug:
	@if not exist scriptFlowEngine\ mkdir scriptFlowEngine\ & if not exist scriptFlowEngine\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd scriptFlowEngine\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\scriptFlowEngine\scriptFlowEngine.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile debug
sub-E--BlsNetPlatformPro-common-common-pro-debug:
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\common\common.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile debug
sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro-debug:
	@if not exist cprModuls\ mkdir cprModuls\ & if not exist cprModuls\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cprModuls\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\cprModuls\cprModuls.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile debug
sub-E--BlsNetPlatformPro-elementParse-elementParse-pro-debug:
	@if not exist elementParse\ mkdir elementParse\ & if not exist elementParse\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd elementParse\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\elementParse\elementParse.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile debug
sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro-debug:
	@if not exist simulatorBase\ mkdir simulatorBase\ & if not exist simulatorBase\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorBase\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorBase\simulatorBase.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile debug
sub-E--BlsNetPlatformPro-transLayer-transLayer-pro-debug:
	@if not exist transLayer\ mkdir transLayer\ & if not exist transLayer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd transLayer\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\transLayer\transLayer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile debug
sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro-debug:
	@if not exist BlsUintTest\ mkdir BlsUintTest\ & if not exist BlsUintTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BlsUintTest\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\BlsUintTest\BlsUintTest.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-E--BlsNetPlatformPro-UI-UI-pro-debug sub-adultParams-debug sub-simulatorEmulateBuild-debug sub-physiologyWatchBar-debug sub-simulatorSymptom-debug sub-scriptFlowEngine-debug sub-E--BlsNetPlatformPro-common-common-pro-debug sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro-debug sub-E--BlsNetPlatformPro-elementParse-elementParse-pro-debug sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro-debug sub-E--BlsNetPlatformPro-transLayer-transLayer-pro-debug sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro-debug

sub-E--BlsNetPlatformPro-UI-UI-pro-release:
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\UI\UI.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile release
sub-adultParams-release:
	@if not exist adultParams\ mkdir adultParams\ & if not exist adultParams\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd adultParams\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\adultParams\adultParams.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile release
sub-simulatorEmulateBuild-release:
	@if not exist simulatorEmulateBuild\ mkdir simulatorEmulateBuild\ & if not exist simulatorEmulateBuild\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorEmulateBuild\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorEmulateBuild\simulatorEmulateBuild.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile release
sub-physiologyWatchBar-release:
	@if not exist physiologyWatchBar\ mkdir physiologyWatchBar\ & if not exist physiologyWatchBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd physiologyWatchBar\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\physiologyWatchBar\physiologyWatchBar.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile release
sub-simulatorSymptom-release:
	@if not exist simulatorSymptom\ mkdir simulatorSymptom\ & if not exist simulatorSymptom\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorSymptom\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorSymptom\simulatorSymptom.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile release
sub-scriptFlowEngine-release:
	@if not exist scriptFlowEngine\ mkdir scriptFlowEngine\ & if not exist scriptFlowEngine\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd scriptFlowEngine\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\scriptFlowEngine\scriptFlowEngine.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile release
sub-E--BlsNetPlatformPro-common-common-pro-release:
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\common\common.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile release
sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro-release:
	@if not exist cprModuls\ mkdir cprModuls\ & if not exist cprModuls\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cprModuls\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\cprModuls\cprModuls.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile release
sub-E--BlsNetPlatformPro-elementParse-elementParse-pro-release:
	@if not exist elementParse\ mkdir elementParse\ & if not exist elementParse\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd elementParse\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\elementParse\elementParse.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile release
sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro-release:
	@if not exist simulatorBase\ mkdir simulatorBase\ & if not exist simulatorBase\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorBase\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorBase\simulatorBase.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile release
sub-E--BlsNetPlatformPro-transLayer-transLayer-pro-release:
	@if not exist transLayer\ mkdir transLayer\ & if not exist transLayer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd transLayer\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\transLayer\transLayer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile release
sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro-release:
	@if not exist BlsUintTest\ mkdir BlsUintTest\ & if not exist BlsUintTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BlsUintTest\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\BlsUintTest\BlsUintTest.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile release
release: sub-E--BlsNetPlatformPro-UI-UI-pro-release sub-adultParams-release sub-simulatorEmulateBuild-release sub-physiologyWatchBar-release sub-simulatorSymptom-release sub-scriptFlowEngine-release sub-E--BlsNetPlatformPro-common-common-pro-release sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro-release sub-E--BlsNetPlatformPro-elementParse-elementParse-pro-release sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro-release sub-E--BlsNetPlatformPro-transLayer-transLayer-pro-release sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro-release

sub-E--BlsNetPlatformPro-UI-UI-pro-check:
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\UI\UI.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile check
sub-adultParams-check:
	@if not exist adultParams\ mkdir adultParams\ & if not exist adultParams\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd adultParams\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\adultParams\adultParams.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile check
sub-simulatorEmulateBuild-check:
	@if not exist simulatorEmulateBuild\ mkdir simulatorEmulateBuild\ & if not exist simulatorEmulateBuild\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorEmulateBuild\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorEmulateBuild\simulatorEmulateBuild.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile check
sub-physiologyWatchBar-check:
	@if not exist physiologyWatchBar\ mkdir physiologyWatchBar\ & if not exist physiologyWatchBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd physiologyWatchBar\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\physiologyWatchBar\physiologyWatchBar.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile check
sub-simulatorSymptom-check:
	@if not exist simulatorSymptom\ mkdir simulatorSymptom\ & if not exist simulatorSymptom\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorSymptom\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorSymptom\simulatorSymptom.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile check
sub-scriptFlowEngine-check:
	@if not exist scriptFlowEngine\ mkdir scriptFlowEngine\ & if not exist scriptFlowEngine\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd scriptFlowEngine\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\scriptFlowEngine\scriptFlowEngine.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile check
sub-E--BlsNetPlatformPro-common-common-pro-check:
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\common\common.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile check
sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro-check:
	@if not exist cprModuls\ mkdir cprModuls\ & if not exist cprModuls\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cprModuls\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\cprModuls\cprModuls.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile check
sub-E--BlsNetPlatformPro-elementParse-elementParse-pro-check:
	@if not exist elementParse\ mkdir elementParse\ & if not exist elementParse\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd elementParse\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\elementParse\elementParse.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile check
sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro-check:
	@if not exist simulatorBase\ mkdir simulatorBase\ & if not exist simulatorBase\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorBase\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorBase\simulatorBase.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile check
sub-E--BlsNetPlatformPro-transLayer-transLayer-pro-check:
	@if not exist transLayer\ mkdir transLayer\ & if not exist transLayer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd transLayer\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\transLayer\transLayer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile check
sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro-check:
	@if not exist BlsUintTest\ mkdir BlsUintTest\ & if not exist BlsUintTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BlsUintTest\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\BlsUintTest\BlsUintTest.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile check
check: sub-E--BlsNetPlatformPro-UI-UI-pro-check sub-adultParams-check sub-simulatorEmulateBuild-check sub-physiologyWatchBar-check sub-simulatorSymptom-check sub-scriptFlowEngine-check sub-E--BlsNetPlatformPro-common-common-pro-check sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro-check sub-E--BlsNetPlatformPro-elementParse-elementParse-pro-check sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro-check sub-E--BlsNetPlatformPro-transLayer-transLayer-pro-check sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro-check

sub-E--BlsNetPlatformPro-UI-UI-pro-benchmark:
	@if not exist UI\ mkdir UI\ & if not exist UI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd UI\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\UI\UI.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-adultParams-benchmark:
	@if not exist adultParams\ mkdir adultParams\ & if not exist adultParams\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd adultParams\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\adultParams\adultParams.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-simulatorEmulateBuild-benchmark:
	@if not exist simulatorEmulateBuild\ mkdir simulatorEmulateBuild\ & if not exist simulatorEmulateBuild\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorEmulateBuild\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorEmulateBuild\simulatorEmulateBuild.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-physiologyWatchBar-benchmark:
	@if not exist physiologyWatchBar\ mkdir physiologyWatchBar\ & if not exist physiologyWatchBar\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd physiologyWatchBar\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\physiologyWatchBar\physiologyWatchBar.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-simulatorSymptom-benchmark:
	@if not exist simulatorSymptom\ mkdir simulatorSymptom\ & if not exist simulatorSymptom\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorSymptom\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorSymptom\simulatorSymptom.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-scriptFlowEngine-benchmark:
	@if not exist scriptFlowEngine\ mkdir scriptFlowEngine\ & if not exist scriptFlowEngine\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd scriptFlowEngine\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\scriptFlowEngine\scriptFlowEngine.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-E--BlsNetPlatformPro-common-common-pro-benchmark:
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\common\common.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro-benchmark:
	@if not exist cprModuls\ mkdir cprModuls\ & if not exist cprModuls\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd cprModuls\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\cprModuls\cprModuls.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-E--BlsNetPlatformPro-elementParse-elementParse-pro-benchmark:
	@if not exist elementParse\ mkdir elementParse\ & if not exist elementParse\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd elementParse\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\elementParse\elementParse.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro-benchmark:
	@if not exist simulatorBase\ mkdir simulatorBase\ & if not exist simulatorBase\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd simulatorBase\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\simulatorBase\simulatorBase.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-E--BlsNetPlatformPro-transLayer-transLayer-pro-benchmark:
	@if not exist transLayer\ mkdir transLayer\ & if not exist transLayer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd transLayer\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\transLayer\transLayer.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro-benchmark:
	@if not exist BlsUintTest\ mkdir BlsUintTest\ & if not exist BlsUintTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BlsUintTest\ && ( if not exist Makefile $(QMAKE) E:\BlsNetPlatformPro\BlsUintTest\BlsUintTest.pro -spec win32-msvc2015 -o Makefile ) && $(MAKE) -f Makefile benchmark
benchmark: sub-E--BlsNetPlatformPro-UI-UI-pro-benchmark sub-adultParams-benchmark sub-simulatorEmulateBuild-benchmark sub-physiologyWatchBar-benchmark sub-simulatorSymptom-benchmark sub-scriptFlowEngine-benchmark sub-E--BlsNetPlatformPro-common-common-pro-benchmark sub-E--BlsNetPlatformPro-cprModuls-cprModuls-pro-benchmark sub-E--BlsNetPlatformPro-elementParse-elementParse-pro-benchmark sub-E--BlsNetPlatformPro-simulatorBase-simulatorBase-pro-benchmark sub-E--BlsNetPlatformPro-transLayer-transLayer-pro-benchmark sub-E--BlsNetPlatformPro-BlsUintTest-BlsUintTest-pro-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

