#ifndef ADULTPARAMS_GLOBAL_H
#define ADULTPARAMS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ADULTPARAMS_LIBRARY)
#  define ADULTPARAMSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ADULTPARAMSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ADULTPARAMS_GLOBAL_H
