#ifndef SIMULATORSYMPTOM_GLOBAL_H
#define SIMULATORSYMPTOM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIMULATORSYMPTOM_LIBRARY)
#  define SIMULATORSYMPTOMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SIMULATORSYMPTOMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SIMULATORSYMPTOM_GLOBAL_H
