#ifndef SIMULATORBASE_GLOBAL_H
#define SIMULATORBASE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIMULATORBASE_LIBRARY)
#  define SIMULATORBASESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SIMULATORBASESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SIMULATORBASE_GLOBAL_H
