#ifndef SIMULATOREMULATEBUILD_GLOBAL_H
#define SIMULATOREMULATEBUILD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIMULATOREMULATEBUILD_LIBRARY)
#  define SIMULATOREMULATEBUILDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SIMULATOREMULATEBUILDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SIMULATOREMULATEBUILD_GLOBAL_H
