#ifndef PHYSIOLOGYWATCHBAR_GLOBAL_H
#define PHYSIOLOGYWATCHBAR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PHYSIOLOGYWATCHBAR_LIBRARY)
#  define PHYSIOLOGYWATCHBARSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PHYSIOLOGYWATCHBARSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PHYSIOLOGYWATCHBAR_GLOBAL_H
