#ifndef SCRIPTFLOWENGINE_GLOBAL_H
#define SCRIPTFLOWENGINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCRIPTFLOWENGINE_LIBRARY)
#  define SCRIPTFLOWENGINESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SCRIPTFLOWENGINESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SCRIPTFLOWENGINE_GLOBAL_H
